---
language: node_js
node_js:
  - "12"

sudo: false
dist: trusty

cache:
  yarn: true


branches:
  only:
    - master
    # npm version tags
    - /^v\d+\.\d+\.\d+/

stages:
  - test
  - additional tests

jobs:
  fail_fast: true

  include:
    # runs tests with current locked deps and linting
    - stage: test
      env: NAME=test
      script:
        - yarn lint:js
        - yarn test

    - stage: additional tests
      env: NAME=floating dependencies
      install: yarn install --no-lockfile --non-interactive
      script: yarn test

    - name: "Node 10"
      node_js: "10"

    - name: "Node 8"
      node_js: "8"


before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash
  - export PATH=$HOME/.yarn/bin:$PATH

install:
  - yarn install

script:
  - yarn test
